# Generated by Django 4.2.13 on 2024-05-12 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='страна')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='должность')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='регион')),
            ],
            options={
                'verbose_name': 'регион',
                'verbose_name_plural': 'регионы',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='навык')),
            ],
            options={
                'verbose_name': 'навык',
                'verbose_name_plural': 'навыки',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='специализация')),
            ],
            options={
                'verbose_name': 'специализация',
                'verbose_name_plural': 'специализации',
            },
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'данные пользователя', 'verbose_name_plural': 'данные пользователей'},
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='citizenship',
        ),
        migrations.AddField(
            model_name='resume',
            name='citizenship1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='гражданство'),
        ),
        migrations.AddField(
            model_name='resume',
            name='citizenship2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='гражданство'),
        ),
        migrations.AddField(
            model_name='resume',
            name='citizenship3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='гражданство'),
        ),
        migrations.AddField(
            model_name='resume',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='телефон'),
        ),
        migrations.AddField(
            model_name='resume',
            name='sex',
            field=models.IntegerField(choices=[(1, 'мужской'), (2, 'женский'), (3, 'не указан')], default=3, verbose_name='пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='surname',
            field=models.TextField(default='', verbose_name='фамилия'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_wage', models.IntegerField(verbose_name='минимальная з/п')),
                ('max_wage', models.IntegerField(verbose_name='максимальная з/п')),
                ('description', models.TextField(verbose_name='описание')),
                ('emloyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='работодатель')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.jobtitle', verbose_name='должность')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакаснии',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.TextField(blank=True, null=True, verbose_name='VK')),
                ('mailru', models.TextField(blank=True, null=True, verbose_name='mail.ru')),
                ('gmail', models.TextField(blank=True, null=True, verbose_name='Gmail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'социальные сети',
                'verbose_name_plural': 'социальные сети',
            },
        ),
        migrations.CreateModel(
            name='Reviev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='время создания')),
                ('mark', models.IntegerField(choices=[(1, 'ужасно'), (2, 'плохо'), (3, 'средне'), (4, 'хорошо'), (5, 'отлично')], verbose_name='оценка')),
                ('text', models.TextField(verbose_name='текст')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='время создания')),
                ('text', models.TextField(verbose_name='текст')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.TextField(verbose_name='название компании')),
                ('text', models.TextField(verbose_name='обязанности и достижения')),
                ('date_begin', models.DateField(verbose_name='дата начала')),
                ('date_end', models.DateField(verbose_name='дата окончания')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.jobtitle', verbose_name='должность')),
            ],
            options={
                'verbose_name': 'опыт работы',
                'verbose_name_plural': 'опыт работы',
            },
        ),
        migrations.CreateModel(
            name='EmployerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='телефон')),
                ('verification', models.BooleanField(verbose_name='верификация')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.region', verbose_name='регион')),
                ('social_networks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.socialnetworks', verbose_name='социальные сети')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'работодатель',
                'verbose_name_plural': 'работодатели',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Среднее'), (2, 'Среднее специальное'), (3, 'Неоконченное высшее'), (4, 'Высшее'), (5, 'Бакалавр'), (6, 'Магистр'), (7, 'Кандидат наук'), (8, 'Доктор наук')], verbose_name='вид образования')),
                ('name_institution', models.TextField(verbose_name='название учебного заведения')),
                ('faculty', models.TextField(verbose_name='факультет')),
                ('end_year', models.DateField(verbose_name='дата выпуска')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.specialization', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'образование',
                'verbose_name_plural': 'образования',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='время создания')),
                ('emloyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_chat', to=settings.AUTH_USER_MODEL, verbose_name='работодатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_chat', to=settings.AUTH_USER_MODEL, verbose_name='кандидат')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чат',
            },
        ),
        migrations.AddField(
            model_name='userdata',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.region', verbose_name='регион'),
        ),
    ]
