# Generated by Django 4.2.13 on 2024-05-12 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0003_country_jobtitle_region_skill_specialization_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviev',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.TextField(default='', verbose_name='имя'),
            preserve_default=False,
        ),
    ]
