# Generated by Django 4.2.13 on 2024-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_vacancy_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(to='portfolio.skill', verbose_name='навыки'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='vacancies',
            field=models.ManyToManyField(to='portfolio.vacancy', verbose_name='отклики'),
        ),
    ]
