# Generated by Django 4.2.13 on 2024-05-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_resume_skills_userdata_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.specialization', verbose_name='специальность'),
        ),
    ]
