# Generated by Django 4.2.13 on 2024-05-15 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0007_alter_education_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='type',
            new_name='type_ed',
        ),
        migrations.AddField(
            model_name='employerdata',
            name='name_company',
            field=models.TextField(default='', verbose_name='название компании'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.chat', verbose_name='чат'),
        ),
        migrations.AddField(
            model_name='review',
            name='emloyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employer_review', to=settings.AUTH_USER_MODEL, verbose_name='работодатель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='отправитель'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='citizenship1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizenship1', to='portfolio.country', verbose_name='гражданство'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='citizenship2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizenship2', to='portfolio.country', verbose_name='гражданство2'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='citizenship3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizenship3', to='portfolio.country', verbose_name='гражданство3'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_review', to=settings.AUTH_USER_MODEL, verbose_name='кандидат'),
        ),
    ]
