# Generated by Django 4.2.13 on 2024-05-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_type_education_type_ed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.resume', verbose_name='резюме'),
        ),
        migrations.AddField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.resume', verbose_name='резюме'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='status',
            field=models.IntegerField(choices=[(1, 'активно ищу работу'), (2, 'рассматриваю входящие предложения'), (3, 'предложили работу, пока думаю'), (4, 'уже выхожу на новое место'), (5, 'не ищу работу')], verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='max_wage',
            field=models.IntegerField(verbose_name='максимальная з/п/мес'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_wage',
            field=models.IntegerField(verbose_name='минимальная з/п/мес'),
        ),
    ]
