# Generated by Django 4.2.13 on 2024-05-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_education_resume_experience_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerdata',
            name='social_networks',
        ),
    ]
