# Generated by Django 4.2.13 on 2024-05-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_emloyer_review_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='emloyer',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='emloyer',
            new_name='employer',
        ),
    ]
