# Generated by Django 4.2.13 on 2024-05-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_emloyer_chat_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='max_wage',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='максимальная з/п/мес'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_wage',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='минимальная з/п/мес'),
        ),
    ]
