# Generated by Django 4.2.13 on 2024-05-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_vacancy_description_alter_vacancy_max_wage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdata',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.region', verbose_name='регион'),
        ),
    ]
