# Generated by Django 4.2.13 on 2024-05-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_employerdata_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdata',
            name='verification',
            field=models.BooleanField(default=True, verbose_name='верификация'),
        ),
    ]
